# .readthedocs.yaml
version: 2

# Build tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - doxygen
  commands:
    - echo "Starting the Doxygen build process..."
    - cd docs/ && doxygen Doxyfile

# Build documentation in the docs/sphinx directory
sphinx:
  configuration: docs/sphinx/conf.py

# Python dependencies
python:
  install:
    - requirements: requirements.txt
